version: '3.5'

services: 
    homeowner-service:
        image: sneyd321/homeowner-service
        depends_on: 
            - homeowner-db
        ports: 
            - 8081:8081
        networks: 
            - roomr-network
        volumes:
            - ./orm-service:/usr/src/app 

        restart: on-failure
   
 
    homeowner-db:
        image: mysql
        
        command: --init-file /data/application/init.sql
        volumes: 
            - ./mysql-volume/init/init.sql:/data/application/init.sql
            - ./mysql-volume/data:/var/lib/mysql

        environment:
            MYSQL_ROOT_PASSWORD: root

        cap_add:
            - SYS_NICE
        networks: 
            - roomr-network
            

networks: 
    roomr-network: