version: '3.5'

services: 
    db-service:
        image: sneyd321/document-service
    
        ports: 
            - 8091:8091
        
        volumes:
            - ./document-service:/usr/src/app 

        restart: on-failure
   

    
        

    
