apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  selector:
    matchLabels:
      run: document-service
  replicas: 1
  template:
    metadata:
      labels:
        run: document-service
    spec:
      containers:
      - name: document-service
        image: sneyd321/document-service
        ports:
        - containerPort: 8091
        
      imagePullSecrets:
        - name: key