apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeowner-service
spec:
  selector:
    matchLabels:
      run: homeowner-service
  replicas: 1
  template:
    metadata:
      labels:
        run: homeowner-service
    spec:
      containers:
      - name: homeowner-service
        image: sneyd321/homeowner-service
        ports:
        - containerPort: 8081
        
      imagePullSecrets:
        - name: key